Improve error handling in Okta module
The original error handling logic was
sometimes throwing errors due to log:
```
File "githubapp/okta.py", line 76, in get_group_members
    print(f"{user.links['self']['href']}: {e}")
TypeError: 'NoneType' object is not subscriptable
```